### PR TITLE
Allow webpack v2

### PR DESCRIPTION
**Pull request by 9renpoto**
- Added webpack build test, multi version ( 6,7,stable )
    - https://travis-ci.org/uncovertruth/react-activity-indicator
- migrate webpack v2
- update dependencies

### CODE REVIEW

**Comment by nii236** [comment]
@9renpotoさん, thanks for the PR! Can you please add some information about what it actually does?

**Comment by 9renpoto** [comment]
oops, update specs !

**Comment by AlexDunmow** [comment]
Thanks @9renpoto!

**Comment by 9renpoto** [comment]
thank you @AlexDunmow !

please activate travis-ci.org !

https://travis-ci.org/blockninja/react-activity-indicator

**Comment by nii236** [comment]
@9renpoto I've gone ahead and enabled Travis CI and started a build.

We've also published the new version to NPM for you.

Thanks again for your contribution!

**Pull request merged**
